#!/bin/sh

stamp=$(stat -c %Y /.dockerenv)

if [ ! -d /host/tmp/goss-bin-$stamp ]; then
   mkdir -p /host/tmp/goss-bin-$stamp
   cp -R /goss/* /host/tmp/goss-bin-$stamp
fi

nsenter --mount=/host/proc/1/ns/mnt -- /tmp/goss-bin-$stamp/goss $@
